name: json-yaml-validate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  json-yaml-validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v5
        with:
          comment: "false" # do not comment on the pull request, the job status says enough
          exclude_file: ".github/config/exclude.txt" # gitignore style file for exclusions
